project:
  type: book
  output-dir: docs

book:
  title: "보건학데이터과학 실습"
  author: "jinha"
  date: "2023. 8. 8."
  chapters:
    - index.qmd
    - part: "I. R 기본"
      chapters:
        - 210_randrstudio.qmd
        - 221_Rbasic1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    #css: style.css
    theme:
      light: flatly
      dark: darkly
  
  pdf:
    documentclass: scrreprt

editor: visual


