project:
  type: book
  output-dir: docs

book:
  title: "보건학데이터과학 실습"
  author: "jinha"
  date: "2023. 8. 8."
  chapters:
    - index.qmd
    - part: "I. R 기본"
      chapters:
        - 210_randrstudio.qmd
        - 221_Rbasic1.qmd
        - 231_dataimportsave.qmd
        - 241_datamanipulation.qmd
        - 243_pivot_longer_wider.qmd
    - part: "II. 데이터 표현 표"
      chapters:
        - 245_datamanipulation_for_table.qmd
        - 247_datamanipulation_for_table_2.qmd
        - 248_datamanipulation_for_table_3.qmd
        - 250_smry_for_table.qmd
    - part: "III. 데이터 표현 플랏"
      chapters:
        - 310_ggplot_basic.qmd
        - 320_kwcs_tutor_plot.qmd
        - 350_statistical_plot.qmd
        - 370_labelled_plot.qmd
        - 380_wave_plot.qmd
    - part: "IV. 여러 형태의 변수값"
      chapters:
        - 410_wrangling_text_01.qmd
        - 510_webscraping_01.qmd
        - 610_webscraping_02.qmd
        - 620_TimeData_01.qmd
        
    - part: "V. AI와 기계학습"
      chapters:
        - 710_GenAI_01.qmd
        - 720_Supervised_01.qmd
        - 730_Supervised_minist_01.qmd
        - 740_Supervised_sentence_01.qmd
    - part: "VI. 소통"
      chapters:
        - 815_rmarkdown02.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    #css: style.css
    theme:
      light: flatly
      dark: darkly
    css: |
      table {
        font-family: 'Times New Roman', serif;
      }
  pdf:
    documentclass: scrreprt
    prefer-html: true
editor: visual

