project:
  type: book
  output-dir: docs

book:
  title: "보건학데이터과학 실습"
  author: "jinha"
  date: "2023. 8. 8."
  chapters:
    - index.qmd
    - part: "I. R 기본"
      chapters:
        - 210_randrstudio.qmd
        - 221_Rbasic1.qmd
        - 231_dataimportsave.qmd
        - 241_datamanipulation.qmd
    - part: "II. 데이터 표현 표"
      chapters:
        - 245_datamanipulation_for_table.qmd
        - 247_datamanipulation_for_table_2.qmd
        - 248_datamanipulation_for_table_3.qmd
        - 250_smry_for_table.qmd
    - part: "III. 데이터 표현 플랏"
      chapters:
        - 310_ggplot_basic.qmd
        - 320_kwcs_tutor_plot.qmd
        - 350_statistical_plot.qmd
        - 370_labelled_plot.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    #css: style.css
    theme:
      light: flatly
      dark: darkly
    css: |
      table {
        font-family: 'Times New Roman', serif;
      }
  pdf:
    documentclass: scrreprt
    prefer-html: true

editor: visual